### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by margartiaville** [joshsten/redmine_jchat#1]
When I entered something, i got this

Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your redMine administrator for assistance.

**Comment by margartiaville** [comment]
I am sure I did chmod on JChat folder

**Comment by joshsten** [comment]
I need to update this again with a newer version I have on a computer that I am not on at the moment. This version should work ok though. What do the logs say? (redmine root/logs/production.log or mongrel.portyouuse.log)

Does the internal error show in the chat frame or does it have the 500 error for the entire page?

**Comment by margartiaville** [comment]
Than you for your reply.
Here is the log:
ActionController::RoutingError (No route matches "/chat/receive_chat" with {:method=>:get}):
  passenger (2.2.11) lib/phusion_passenger/rack/request_handler.rb:92:in `process_request'
  passenger (2.2.11) lib/phusion_passenger/abstract_request_handler.rb:207:in`main_loop'
  passenger (2.2.11) lib/phusion_passenger/railz/application_spawner.rb:418:in `start_request_handler'
  passenger (2.2.11) lib/phusion_passenger/railz/application_spawner.rb:358:in`handle_spawn_application'
  passenger (2.2.11) lib/phusion_passenger/utils.rb:185:in `safe_fork'
  passenger (2.2.11) lib/phusion_passenger/railz/application_spawner.rb:354:in`handle_spawn_application'
  passenger (2.2.11) lib/phusion_passenger/abstract_server.rb:352:in `__send__'
  passenger (2.2.11) lib/phusion_passenger/abstract_server.rb:352:in`main_loop'
  passenger (2.2.11) lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
  passenger (2.2.11) lib/phusion_passenger/abstract_server.rb:163:in`start'
  passenger (2.2.11) lib/phusion_passenger/railz/application_spawner.rb:213:in `start'
  passenger (2.2.11) lib/phusion_passenger/spawn_manager.rb:262:in`spawn_rails_application'
  passenger (2.2.11) lib/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
  passenger (2.2.11) lib/phusion_passenger/spawn_manager.rb:256:in`spawn_rails_application'
  passenger (2.2.11) lib/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
  passenger (2.2.11) lib/phusion_passenger/abstract_server_collection.rb:79:in`synchronize'
  passenger (2.2.11) lib/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
  passenger (2.2.11) lib/phusion_passenger/spawn_manager.rb:154:in`spawn_application'
  passenger (2.2.11) lib/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
  passenger (2.2.11) lib/phusion_passenger/abstract_server.rb:352:in`**send**'
  passenger (2.2.11) lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
  passenger (2.2.11) lib/phusion_passenger/abstract_server.rb:196:in`start_synchronously'

Rendering /home/data/rails/redmine/public/404.html (404 Not Found)

The internal error shows in the chat frame only.

Thank you.
again, this is a really nice plugin

**Comment by joshsten** [comment]
https://myprojectmanager.mysite.com/chat/receive_chat
https://myprojectmanager.mysite.com/chat

Replace the first part with your Redmine URL. Do either of these work? There might be a difference with passenger. I will try to setup Redmine with passenger and test it over the next few days.

It's possible passenger may not like the extra first slash which I am using to refer to the root of the site. If the above URLs function (Do not generate 404 or 500 errors) then I think I can post a fix.

**Comment by margartiaville** [comment]
second one works.

first doesnt, it shows:
Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your redMine administrator for assistance.

**Comment by margartiaville** [comment]
should i update passenger?

**Comment by joshsten** [comment]
No I think it's a problem with my code. I'll try to do a clean install into a fresh VM using passenger tonight or tomorrow evening. I released it to the Redmine plug-in list a little prematurely.

**Comment by joshsten** [comment]
I did some important fixes. Would you be able to test the newest version when you get around to it? I would recommend running a new git clone and db migrate as I renamed the project to be consistent with other plugins. You may need to also remove/rename the chat table in the redmine database (due to the name change).

**Comment by margartiaville** [comment]
yes, I would like to. 
what is the name of the table?
can I do it now?

**Comment by margartiaville** [comment]
is the table named "chat"?

**Comment by margartiaville** [comment]
sorry, "chats"?

**Comment by margartiaville** [comment]
holy, this is big.
it works perfectly!

thanks man

**Comment by margartiaville** [comment]
seems IE 6 doesnt show properly, teammate complained.
but i dont care.

**Comment by margartiaville** [comment]
u may add a tab showing all chat history.
hoho

**Comment by margartiaville** [comment]
could you make a little improvement,  scrolling the bar to the bottom automatically when got others' messages

**Comment by joshsten** [comment]
If it's too big you can edit the assets/css/main.css and tinker with the sizes. 

I'll try to get I.E. compatibility, a tab option, and the scroll bar thing worked out this weekend.

The scroll bar thing is my next todo.

And I'm glad it works :) Let me know if there is anything that becomes annoying as you use it or something that would be nice to have aside from the above.

**Comment by margartiaville** [comment]
thank you so much for the reply.
is it possible to add a setting that it can show full name of user in the chat frame or not, or even show "me" for user himself?

sorry, i said big, means i feel this is an amazing thing to me. 

thank you
