### ISSUE TITLE
no more choosable settings

### ISSUE THREAD

**Issue by cforce** [joshsten/redmine_jchat#11]
All settings are greyed out /disabled now. As i remember there was some settings in earlier version which can be eanbled or disabled, like color of my messages..Is this all future work now?

**Comment by joshsten** [comment]
Yes it is future work. In the prior version the settings were in place, but didn't have any implementation (They were stubs). It was misleading to have them able to be set and unset so I decided to set the disabled property until I get it put together. Some of the functionality is implemented, but I haven't plugged it into the configuration panel yet. That's next on my todo list along with getting the "new message" and scrolling functionality implemented in a more reliable way.
