### ISSUE TITLE
Feature Request:xmpp/jabber client extension

### ISSUE THREAD

**Issue by cforce** [joshsten/redmine_jchat#13]
We are using redmine messenger (https://github.com/mszczytowski/redmine_messenger) in conjuction with openfire xmpp/Jabber server .An Jabber/XMMP Server offers all possibilities of chat features you can imagine, like group chat or pm, queing and so on. The client api is quite easy, the only thing is missing good webchat redmine to offer direct accces to a projects team room. The redmine messenger plugins already integrates new personal menue of the top left where some can enter its jabber-id and can authorise against the redmine bot. The jchat plugin could just read the jabber-id, connect the user to the in redmine messenger settings also configured  team room and its xmpp/jabber server via xmpp protocol (see redmine messenger "gem install xmpp4r"). I know thre is also a feature requetst for a team room and group chat, which can be done on a xmpp server easily. Either you can use the redmine messenger plugin as base or just have a look there and copy the code which is needed. 

Settings up an openfire server is done in 10 minutes..see here..
http://www.igniterealtime.org/builds/openfire/docs/latest/documentation/install-guide.html

**Comment by joshsten** [comment]
I wanted to comment on this to let you know:
Our environment recently developed a use for this functionality for messaging from a network monitoring server, I'll be attempting to put something together over the next few weeks.

**Comment by cforce** [comment]
Thats sounds great - i will test and localize to german. Looking forward for your contribution!
