### ISSUE TITLE
Feature Request: See Who's Online

### ISSUE THREAD

**Issue by bennun** [joshsten/redmine_jchat#19]
This is a great plugin, very simple, easy to use. I'm excited about it and we'll be using it more extensively. I'd like to see a feature to determine see who's online. This will prevent users from trying to chat for support issues, and not realizing we're all sleeping!

**Comment by joshsten** [comment]
Thank you for your compliment :)

I tried to show who was online initially, but Redmine doesn't keep track of
that information internally so I would need to some major work.

I hope to have more time this summer to implement the features everyone has
been requesting including this one.

Best Regards,
Josh

**Comment by bennun** [comment]
Excellent, thanks for the update! - Josh
