### ISSUE TITLE
The requested URL /chat/receive_chat was not found on this server.

### ISSUE THREAD

**Issue by joaomoraes** [joshsten/redmine_jchat#2]
I'm getting this error message when i try to acess the chat tab:

<pre>
The requested URL /chat/receive_chat was not found on this server.
</pre>

Do you know how can i solve this?

My redmine version is 1.0.3
Bitnami Install
Windows 7
Mysql 5.0.83

**Comment by joshsten** [comment]
When you say chat tab - Do you mean when you click on the dates of the messages?
Does sending and receiving messages work?

**Comment by joaomoraes** [comment]
No, the box where all the chat messages should appear is showing the above message. I think the link at the right bottom is working as intended, showing the chat box and the input box. 
Unfortunately my poor RoR and Redmine knowledge does not help me to find what I'm doing wrong.

**Comment by joshsten** [comment]
I'll look at this this evening. It's possible something is different in 1.0.3 (Last tested in 1.0.1) I'll check compatibilities and make fixes if required tonight.

**Comment by joaomoraes** [comment]
Ty, I really liked the idea of having a chat embedded in Redmine =)

**Comment by joshsten** [comment]
I have figured out your issue. I did a bitnami install, and figured out that my controller actions are being applied relative to the site root rather than the redmine root. I am working on a patch to do things relative to the redmine base location now.

**Comment by joshsten** [comment]
It may take me a bit to get the fix implemented. To do your own fix edit assets/javascript/main.js and everywhere /chat (you can do search for /chat) appears prepend the base URL with your base location. On bitnami the needed prepended URL is /redmine.

You also need to do the same procedure to apps/views/chat/_receive_chat.erb script.

I'm looking into ways to fix this automatically.

**Comment by joaomoraes** [comment]
Thanks for your reply Josh.

I can only try this @ work on tuesday but I will inform here if everything goes well =)

**Comment by joaomoraes** [comment]
I accidentally closed the issue, sorry.

**Comment by ron-fu** [comment]
So after I got the chat installed on my bitnami VM , I run into the error above.
I changed  the entry /chat into /redmine in the following 3 files
1 line in: /opt/bitnami/apps/redmine/vendor/plugins/redmine_jchat/app/views/chat/_receive_chat.erb 
2 lines in:  /opt/bitnami/apps/redmine/public/plugin_assets/redmine_jchat/javascripts/main.js
2 Lines in: /opt/bitnami/apps/redmine/vendor/plugins/redmine_jchat/assets/javascripts/main.js
I get :
Page not found
The page you were trying to access doesn't exist or has been removed.

The access_log is showing:
POST /redmine/receive_chat HTTP/1.1" 404 484 
so the path isn't right. I'll try /redmine/chat next week.

regards Ron

**Comment by ron-fu** [comment]
just changed the path to /redmine/chat and that seems to work.
But no message can be send 
entries in access_log are:
"POST /redmine/chat/receive_chat HTTP/1.1" 200 1
 "POST /chat/send_chat HTTP/1.1" 404 212

but where to change the path for send??

regards Ron

**Comment by ron-fu** [comment]
so got it! I missed to change the /chat/send_chat path in main.js to redmine/chat/send_chat

Thanks for your plugin! 
As seen in the feature request a group/project chatroom would be perfect!

**Comment by joshsten** [comment]
I won't be able to implement that feature for a bit, I need to do a little development and testing on a new javascript implementation to fix some timing dependent issues in the current implementation in regard to message flashing and scrolling the chat frame at the correct times. I hope to get this functionally working within a week. I need to also address the issue you ran into here. I have a month long break coming up in a few weeks, at which point I will look at adding segregation options for chats like chats for specific projects.  I appreciate the thanks, and I hope it works well for you.

**Comment by coldstream** [comment]
Hi joshsten,
I really like your plugin and I have it implemented on Redmine 1.1.2 using Bitnami (MacOS version).  Any plans to make the feature enhancements in the near future?  I know you are a busy guy but wanted to find out if this was something I could commit to for my project teams.

Todd

**Comment by joshsten** [comment]
coldstream,

I do not realistically see any time for me to do any major work on it
opening up until summer when I have my weekends and evenings more open.

Very Best Regards.
Josh
.

**Comment by joshsten** [comment]
This issue should now be resolved with the recent line of commits.

Testing showed issue as resolved.
