### ISSUE TITLE
Can´t see the chat

### ISSUE THREAD

**Issue by ideabcn** [joshsten/redmine_jchat#3]
Hi Josh,
I installed your plugin in a Redmine 1.0.3 Linux OS (shared host)
I can see the plugin installed in  administration/plugins, but no text box or button or chat link is visible. I've tried to change the theme to classic or alternate, bot didn't work.
Any clue how to solve this?
Thanks!

**Comment by joshsten** [comment]
I'll try to take a look at it this evening. 1.0.1 is the last I have verified working. I need to test it on 1.03. If any fixes are required I'll make them tonight.

Thank you for the issue report.

Something that may help - When you view the HTML of the page after logging in and do a search through the HTML for "chat" do you get any results i.e. divs?

**Comment by joshsten** [comment]
I tested 1.03 and every thing looks good. I am still doing some testing, so something might come up. One other thing that will help me resolve your issue, does the text at bottom say:

"Powered by Redmine © 2006-2010 Jean-Philippe Lang - Enhanced"
or just:
"Powered by Redmine © 2006-2010 Jean-Philippe Lang"

A list of your installed plugins may help. It's possible one of them may have been overriding the same layout the old version was.  If this was indeed the issue, the newest version I just committed should be fixed in this regard.

**Comment by ideabcn** [comment]
Hi Josh

Thanks for your quick reply!

The bottom text is: "Powered by Redmine © 2006-2010 Jean-Philippe Lang"

And here is my plugin list installed:

Customer plugin
This is a plugin for Redmine that can be used to track basic customer information
https://projects.littlestreamsoftware.com/projects/redmine-customers
Eric Davis  0.2.0   

Projects Tree View plugin
This is a Redmine plugin which will turn the projects page into a tree view
Chris Peterson  0.0.4   

redmine ics export plugin (aka redmics)
ICalendar view of issue- and version-deadlines
http://code.google.com/p/redmics/
Frank Schwarz   1.0.2   

Redmine JChat
Provides a team chat similiar to Google's/Facebooks chat.
Joshua Enfield  0.1.0   

I hope this help to clarify the issue!

BR,
Daniel

**Comment by ron-fu** [comment]
Hi Josh,
I just installed your plugin on a fresh Bitnami Redmine 1.03 VM.
I can see the plugin listed but no chat. The source code of the "homepage" is showing several j-chat entries in header and body.

Do I miss something? Or do I need to install some Apache modules?

Regards
Ron

**Comment by ron-fu** [comment]
Found a entry in redmine produktion.log 

Processing ApplicationController#index (for 192.168.1.91 at 2010-11-25 10:38:55) [GET]

ActionController::RoutingError (No route matches "/plugin_assets/redmine_jchat/stylesheets/" with {:method=>:get}):

Rendering /opt/bitnami/apps/redmine/public/404.html (404 Not Found)

**Comment by ron-fu** [comment]
Hi Josh,
found the chat after a new install, the button should be in a other colour then light grey! maybe the redmine blue?? 

But get now the  "The requested URL /chat/receive_chat was not found on this" error. 
I'll writing next in this issue!

regards Ron

**Comment by joshsten** [comment]
I did a bitnami install last week, and I think your problem may be that the root install on bitnami is under a nonroot folder "/redmine" This causes some pathing issues that I didn't account for. I am working on a solution, but it will probably be Wednesday or the weekened before I can really look into getting anything actually done. As ron-fu I believe figured out in the other thread you can change the paths in the main.js and main.css files in the assets folder of the plugin.

Best Regards,
Josh

**Comment by ideabcn** [comment]
After a reinstall of plugins (project tree and Jchat) I finally can see the "Chat" button. My redmine installation is in a non root install as I'm using a shared host. So far it works fine, and I keep looking for new updates and improvements.
Keep up the good work!
A little suggestion, if possible, make a chat button clor change when new message (not readed), not twinke, just a color change.

BR,
Daniel

**Comment by mojobiri** [comment]
Hello! Seems i have the same problem with chat as ron-fu:
Processing ApplicationController#index (for 10.8.0.117 at 2011-03-16 03:29:38) [GET]

ActionController::RoutingError (No route matches "/plugin_assets/redmine_jchat/javascripts/main.js" with {:method=>:get}):

Rendering /usr/share/redmine/public/404.html (404 Not Found)

You said that "you can change the paths in the main.js and main.css files in the assets folder of the plugin.". I was looking for those strings and i can't figure out what strings(paths, there is no paths) should i change? Thanks! I bielive it's a good plugin. Keep going!

**Comment by joshsten** [comment]
Do you have your Redmine install in a non-site root location? i.e. www.mysite.com/redmine vs. www.mysite.com (where www.mysite.com can be just the ip)

By default the paths reference against the site root, so if your Redmine is in a different location you need to add the parts after the site root (/redmine in the example above).

I hope to eventually address this with dynamically generated javascript and css files, but I have unfortunantly been extremely busy the last few months.

By nature of your error it may be helpful to try to navigate to the javascript/css file in your browser, and see what the path ends up being. 

If this advice does not resolve your issue let me know, we will get it worked out. Links to relevant lines mentioned below:

Lines 117 and 131 in main.js, and 54, 60 in main.css

https://github.com/joshsten/redmine_jchat/blob/master/assets/javascripts/main.js#L117
https://github.com/joshsten/redmine_jchat/blob/master/assets/javascripts/main.js#L131
https://github.com/joshsten/redmine_jchat/blob/master/assets/stylesheets/main.css#L54
https://github.com/joshsten/redmine_jchat/blob/master/assets/stylesheets/main.css#L60

**Comment by joshsten** [comment]
Issue should now be resolved with latest commits.

I believe this issue was a pathing problem which has now been tested as resolved.

**Comment by ideabcn** [comment]
Thanks, I'll give it another try soon.
