### ISSUE TITLE
403 Forbidden on accessing any ressource

### ISSUE THREAD

**Issue by cforce** [joshsten/redmine_jchat#8]
Since we installed the plugin we have abnormal occourence of "403 Forbidden" accesing any ressource on the redmine server. After some seconds and some rertries on the same url access works again - no relogin is needed. This problem goes away as soon as we deinstall the plugin.
We also noticed a lot of requests by the chat plugin, maybe thats the cause for the access bug. 
172.16.104.3 - - [23/Nov/2010:12:06:51 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:06:51 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:06:56 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:06:56 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:07:01 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:07:01 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:07:06 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:07:06 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:07:11 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:07:11 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:07:16 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:07:16 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:07:21 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:07:21 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:07:26 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:07:26 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:07:31 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"
172.16.104.3 - - [23/Nov/2010:12:07:32 +0100] "POST /chat/receive_chat HTTP/1.1" 200 777 "https://sid-repo.meine-gruppe.de/projects/prodtwicklungundorg/wiki/JavaEntwicklerarbeitsplatz" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.44 Safari/534.7"

We are using Redmine  on Debian Lenny : Redmine 1.0.3
- Ruby: RMagick, Ruby 1.8.7, libzlib-ruby, libyaml-ruby, libopenssl-ruby, librmagick-ruby, rake (>=0.8.3), ruby-dev, RubyGems 1.3.7, Phusion Passenger 2.2.9 (gem install passenger), Ruby on Rails 2.3.5 (gem install rails -v=2.3.5), Ruby Rack 1.0.1 (gem install rack -v=1.0.1), C bindings for Ruby (gem install mysql)
- Apache: apache2, apache2-dev, libapache2-svn, Subversion 1.6.13, build-essential, libapache-dbi-perl, libapache2-mod-perl2, libdigest-sha1-perl, libdbd-mysql-perl, libauthen-simple-ldap-perl, libio-socket-ssl-perl
- MySQL Client: libmysqlclient15-dev

**Comment by joshsten** [comment]
I also think this is probably caused by the frequent requests. This can be alleviated by tweaking the interval in the main.js file on line 134. The frequency number controls the update interval in seconds. I will attempt to move this into the configuration panel as my time allows.

The only other approach I aware of to do this is via a commet model, but that requires special server configuration which I am trying to avoid. To alleviate the issues the best approach I can think of is to reduce the update interval.
